name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password:  ${{ secrets.DOCKERHUB_PWD }}
        logout: false
      
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.2.0
      with:
       push: true
       tags: index.docker.io/${{ secrets.DOCKERHUB_USER }}/sdc_technikum-wien:covid_dashboard_${{ github.sha }}
       file: ./Dockerfile

    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2.2.5
      with:
        app-name: WA-SDC-Covid-Dashboard
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        slot-name: 'production'
        images: index.docker.io/${{ secrets.DOCKERHUB_USER }}/sdc_technikum-wien:covid_dashboard_${{ github.sha }}
        
